theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
nav:
  - title: redame
    url: readme.html
    subnav:
      - title: Heroku
        url: test/test.html
        subnav:
          - title: Jekyll on Heroku
            url: jekyll-on-heroku.html
  - title: Contact
    url: contact.html

