baseurl: okmechak.github.io
url: okmechak.github.io

title: DWNM

theme: jekyll-theme-cayman

description: "Персональний вебсайт"

author: "Олег Кмечак"

plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

nav:
  - title: redame
    url: readme.html
    subnav:
      - title: Heroku
        url: test/test.html
        subnav:
          - title: Jekyll on Heroku
            url: jekyll-on-heroku.html
  - title: Contact
    url: contact.html

markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]